FROM demoregistry.dataman-inc.com/library/centos7-base:20160907193907 
MAINTAINER pro zpang@dataman-inc.com

ENV CADVISOR_VERSION="v0.23.8"

RUN wget -O /cadvisor https://github.com/google/cadvisor/releases/download/$CADVISOR_VERSION/cadvisor && \
    chmod 755 /cadvisor 

ENTRYPOINT ["/cadvisor"]
