FROM demoregistry.dataman-inc.com/library/google-cadvisor:v0.26.1 
MAINTAINER pro zpang@dataman-inc.com

# time 
RUN apk add --update tzdata && rm -rf /var/cache/apk/*
RUN cp /usr/share/zoneinfo/Hongkong /etc/localtime

# add gnu find 
RUN apk add --update findutils && rm -rf /var/cache/apk/*
